# Generated by Django 5.2.3 on 2025-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(blank=True, max_length=100)),
                ('published_date', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('isbn', models.CharField(blank=True, default='unknown', max_length=20)),
                ('publisher', models.CharField(blank=True, default='미상', max_length=100)),
            ],
        ),
    ]
