# Generated by Django 5.2.3 on 2025-06-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
